apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - streamlit.yaml
  - ray-service.yaml
images:
  - name: public.ecr.aws/h3o5n2r0/gen-ai-demo/dogbooth-app
    newName: docker.io/captcloud01/dogbooth-app
    newTag: 4c696dd224497f896046cb91b8b03dc0ec7574ce
